server:
  port: 8072
  
logstash.host: 3.136.161.26:5000
 
logging: 
  config: classpath:logback-delayed.xml
  
 
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eurekaserver:8070/eureka/
      
spring:
  zipkin:
    baseUrl: http://zipkin:9411
  sleuth:
    sampler:
      percentage: 1
  cloud:
    loadbalancer.ribbon.enabled: false
    gateway:
        routes:
   
    
management:
  endpoints:
    web:
      exposure:
        include: "*"
